api-platform/demo

- app/config/services.yml
- features/books.feature
- src/AppBundle/Entity/Book.php
- src/AppBundle/Entity/Review.php
- web/config.php
> Add filter on itemReviewed

- app/config/parameters.yml.dist
Like this I assume?
Lmk when you deploy it :).
> Allow all CORS

- README.md
This PR fixes the missing installation instructions for #19
> Added installation instructions for #19

- api/composer.lock
Fix https://github.com/api-platform/demo/issues/28
> Bump dependencies

- api/composer.json
- api/composer.lock
- api/symfony.lock
Hi,
In order to execute `docker-compose up`  properly after a security report, we have to update the `api-platform/api-pack` version.
see #68
> Update composer.json and associated lock files.

- .travis.yml
- ci/before_deploy
- ci/clean
- ci/deploy
- ci/test
> Add project name label in namespace

- api/composer.lock
- api/symfony.lock
Currently the dependencies are not up to date.
> Fix: dependencies version because it have known vulnerabilities

- api/composer.json
- api/composer.lock
- api/config/packages/api_platform.yaml
- api/src/Entity/Book.php
- api/symfony.lock
- ci/test
Also upgrades to Symfony 4.3 and API Platform 2.5 (dev).
> Enable JSON Merge Patch

- docs/CONTRIBUTING.md
| Bug fix?      | yes (in docs) 
| New feature?  | no 
| Tickets       | fixes #... 
| Doc PR        | api-platform/docs#...
> fixed broken link to LICENSE

- ci/test
Signed-off-by: Pascal Borreli <pascal@borreli.com>
> Testing memory optimisation (travis is crashing too often)

- api/src/Entity/Review.php
- client/src/components/review/Form.js
| New feature?  | no 
| Tickets       | fixes #... 
| Doc PR        | api-platform/docs#...
> fixed form fields placeholders

- .travis.yml
- api/.env
- api/composer.json
- api/composer.lock
- api/config/bundles.php
- api/config/packages/csa_guzzle.yaml
- api/config/packages/doctrine.yaml
- api/config/packages/messenger.yaml
- api/config/packages/test/doctrine.yaml
- api/config/services.yaml
- api/features/bootstrap/MessengerContext.php
- api/fixtures/books.yml
- api/src/Entity/Book.php
- api/src/Handler/BookHandler.php
- api/symfony.lock
- api/tests/BooksTest.php
- ci/test
- client/features/features/books.feature
- client/features/pages/book.js
- client/features/step_definitions/books.js
- client/features/support/assert.js
- client/features/support/form.js
- client/features/support/navigation.js
- client/src/actions/book/show.js
- client/src/components/book/Show.js
- client/src/reducers/book/show.js
- docker-compose.yml
> Install & configure Mercure + Postgres PUB/SUB

- api/.env
- api/config/packages/prod/framework.yaml
- api/config/services.yaml
- api/helm/api/templates/configmap.yaml
- api/helm/api/templates/php-deployment.yaml
- api/helm/api/values.yaml
- api/src/Handler/BookHandler.php
- ci/deploy
| Tickets       | N/A
| Doc PR        | N/A
Mercure was not working for generating the book cover.
> Fix Mercure (book cover)

- api/config/packages/messenger.yaml
| Tickets       | N/A
| Doc PR        | N/A
> Fix Messenger DSN in prod

- admin/Dockerfile
- admin/package.json
- admin/yarn.lock
| Tickets       | N/A
| Doc PR        | N/A
Use the new API Platform Admin 2.
> Upgrade admin and bump dependencies

- api/helm/api/values.yaml
| Bug fix?      | yes but no but yes
> Fixed cors

- api/Dockerfile
- api/docker/php/docker-entrypoint.sh
- api/src/Handler/BookHandler.php
> Fix reload fixtures

- .github/workflows/deploy.yml
> Disable deploy on PR from fork

- .github/workflows/test.yml
- api/composer.json
- api/composer.lock
- api/phpstan.neon
- api/src/DataProvider/Extension/TopBookCollectionExtensionInterface.php
- api/src/DataProvider/Extension/TopBookPaginationExtension.php
- api/src/DataProvider/TopBookCollectionDataProvider.php
- api/src/DataProvider/TopBookItemDataProvider.php
- api/src/Doctrine/ORM/Mapping/ResourceNamingStrategy.php
- api/src/Entity/Book.php
- api/src/Entity/Parchment.php
- api/src/Entity/Review.php
- api/src/Entity/User.php
- api/src/Handler/BookHandler.php
- api/src/Repository/TopBook/TopBookCachedDataRepository.php
- api/src/Repository/TopBook/TopBookDataInterface.php
- api/src/Repository/TopBook/TopBookDataRepository.php
- api/symfony.lock
- api/tests/BooksTest.php
- api/tests/Entity/TopBooksTest.php
| New feature?  | yes
| Tickets       | fixes #163 
| Doc PR        | NA. Doc in composer.json + phpstan.neon
This adds the PHPStan static analysis at the maximum level.
> Add PHPStan

- admin/package.json
- admin/src/App.js
- admin/src/authProvider.js
- admin/yarn.lock
| Tickets       | no
| Doc PR        | no
* Improve `checkAuth` with token expiration check
* Improve `checkError` with `args.status` and `args.resource.status` checks
> Fix and improve demo auth

- admin/package.json
- admin/src/App.js
- admin/src/index.js
- admin/src/layout/Login.js
- admin/yarn.lock
| Tickets       | N/A
| Doc PR        | N/A
Update to follow the latest changes for the [authentication support](https://api-platform.com/docs/admin/authentication-support/).
> [Admin] Better auth and bump dependencies

- .github/workflows/cleanup.yml
- api/public/index.php
- api/src/Handler/BookHandler.php
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| Deprecations? | yes/no
| Tickets       | fixes #184
| Doc PR        | api-platform/docs#...
> Fixes #184

- pwa/config/entrypoint.ts
- pwa/pages/admin/index.tsx
- pwa/utils/authProvider.tsx
- pwa/utils/dataAccess.ts
To be uniform with the client-generator component.
See also: https://github.com/api-platform/api-platform/pull/1939
> fix: export ENTRYPOINT in entrypoint.ts

- api/docker/php/php-fpm.d/zz-docker.conf
Copied from https://github.com/api-platform/api-platform/pull/1997
> fix: set php-fpm process_control_timeout

- api/composer.json
- api/composer.lock
According to https://github.com/nelmio/alice/issues/1089#issuecomment-918412004, packagist will now pick the fork of theofidry.
> fix/alice-bundle remove vcs repository for alice-bundle

- api/docker/php/docker-entrypoint.sh
| Tickets       | https://github.com/api-platform/docs/issues/1446
| Doc PR        | https://github.com/api-platform/docs/pull/1448
The command was added to the bundle in v2.11.
Composer install was moved first to ensure that the bundle is installed.
This now attempts the permission modification (`setfacl`) irrespective of
the previous existence of the key files. While the cost of this operation
are certainly not zero, it ensures the permissions are as intended no
matter how the key files came to be and leaves the configuration of the
key file name entirely with the bundle/.env file.
> feat: use JWT bundle's command to create keys

- .github/workflows/cd.yml
update external-dns to filter the same domain than ingress host
> ci: External dns domain filter

- helm/api-platform/values.yaml
This add a PersistentVolume to the PostgreSQL Pod for fixture persistence.
> fix: add persisent volume to postgresql

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/cleanup.yml
> fix: update GitHub Actions workflows

- api/Dockerfile
| Tickets       | https://github.com/api-platform/demo/issues/273
| Doc PR        | todo
> fix: JWT keys permission on Docker for Mac

- helm/api-platform/values.yaml
add a memory limit to limit caddy high memory usage.
> Add memory limit on caddy

- .github/workflows/cd.yml
> Add deploy trigger

- .github/workflows/cd.yml
- .github/workflows/deploy.yml
- api/Dockerfile
- api/docker/caddy/Caddyfile
- docker-compose.yml
- helm/api-platform/templates/configmap.yaml
- helm/api-platform/templates/cronjob.yaml
- helm/api-platform/templates/deployment.yaml
- helm/api-platform/templates/fixtures-job.yaml
- helm/api-platform/values.yaml
This is necessary for tests in the client generator (and for people).
> fix: add localhost to cors

- helm/api-platform/templates/deployment.yaml
- helm/api-platform/values.yaml
- Reduce resources requests to limit demo Kubernetes cluster size,
- replace long initialDelaySeconds in readiness and liveness probes by a startupProbe.
> Helm tuning

- .github/workflows/cd.yml
| Tickets       | 
| Doc PR        | 
On main branch, deploy the `latest` image (default image tag when building on `default_branch`)
> on main, deploy latest image tag

- helm/api-platform/templates/deployment.yaml
Increase probes delay and fork less process in command probes
> probes tuning

- .github/workflows/ci.yml
- api/src/DataFixtures/Story/DefaultReviewsStory.php
- pwa/.gitignore
- pwa/components/admin/Admin.tsx
- pwa/package.json
- pwa/playwright.config.ts
- pwa/pnpm-lock.yaml
- pwa/tests/Books.spec.ts
- pwa/tests/HomePage.spec.ts
- pwa/tests/Page.ts
- pwa/tests/Reviews.spec.ts
- pwa/tests/admin/OpenApi/Books.spec.ts
- pwa/tests/admin/OpenApi/Reviews.spec.ts
- pwa/tests/admin/OpenApi/TopBooks.spec.ts
- pwa/tests/admin/PageAdmin.ts
- pwa/tests/admin/hydra/Books.spec.ts
- pwa/tests/admin/hydra/Reviews.spec.ts
- pwa/tests/admin/hydra/TopBooks.spec.ts
Add e2e test with playwright api-platform 3
> Add e2e tests with playwright

- api/composer.lock
- api/config/packages/api_platform.yaml
- api/src/Security/Http/Protection/ResourceResourceHandler.php
- helm/api-platform/Chart.yaml
Update doctrine/orm to 3.2.0 to benefits [hotfix](https://github.com/doctrine/orm/commit/baf96cdad45d44e68dcd6400cdd4969e954ec524)
> chore: update doctrine/orm for hotfix

- helm/api-platform/values.yaml
| Branch?       | main for features / current stable version branch for bug fixes 
| Tickets       | Closes #..., closes #... 
| Doc PR        | api-platform/docs#...
> reduce keycloak cpu request
