api-platform/demo

.travis.yml
app/config/config.yml
src/AppBundle/Entity/Book.php
src/AppBundle/Entity/Review.php
src/AppBundle/Resources/fixtures/orm/books.yml

This aims to fix fixtures loading which looks broken.
I fixed the mysql server version to avoid https://github.com/doctrine/DoctrineBundle/issues/351.

Fix fixtures loading

---

api/composer.json
api/docker/php/docker-entrypoint.sh

| Tests pass?   | yes
| Fixed tickets | #30

Fix demo installation

---

ci/test.sh
client/.eslintrc
client/package.json
client/yarn.lock

| New feature?  | yes
| Tests pass?   | yes
| Fixed tickets | #54

Configure eslint

---

ci/before_deploy.sh
ci/before_install.sh
ci/deploy.sh
ci/test.sh
client/.dockerignore
client/.gitignore
client/Dockerfile
client/docker/docker-entrypoint.sh
client/features/features/books.feature
client/features/hooks.js
client/features/pages/book.js
client/features/pages/index.js
client/features/server.js
client/features/step_definitions/books.js
client/features/support/assert.js
client/features/support/form.js
client/features/support/index.js
client/features/support/navigation.js
client/features/support/scope.js
client/features/world.js
client/package.json
client/yarn.lock

| New feature?  | yes
| Tests pass?   | yes
| Fixed tickets | #53

Add Puppeteer

---

api/.env
ci/before_deploy
docker-compose.yml

Also add instructions for user on how to generate MERCURE_JWT_SECRET easily
"Unsecure" -> "Insecure"

Fix MERCURE_JWT_SECRET env var which was not set in the Travis CI build

---

api/helm/api/values.yaml

To avoid CORS rejection when using client-generator we should enable this kind of origins
For info: regex battery test -> https://regex101.com/r/3CUlV8/2
| Tests pass?   | not sure of this (I can't install project ATM)

feat: authorize localhost call to demo api

---

ci/deploy

By default, the generated JWT expires after 1 hour... It's obviously too short to be useful in the demo.

Fix Mercure support

---

api/helm/api/values.yaml
ci/deploy
docker-compose.yml

[Since 0.10](https://github.com/dunglas/mercure/blob/master/docs/UPGRADE.md), Mercure changed its way of receiving the CORS: it now needs a space separated list instead of coma separated.

Fix Mercure CORS

---

README.md
api/Dockerfile

"api" compoent doesn't start with composer2 (latest), forcing dependency to composer 1 for now.
| Tickets       | NA.
| Doc PR        | NA.

docker: force composer 1 for API component

---

.github/workflows/deploy.yml
api/helm/api/Chart.lock
api/helm/api/Chart.yaml

| Deprecations? | yes
| Tickets       | fixes #167 
| Doc PR        | NA.
This is to fix the following error:
```
`Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
Error: Process completed with exit code 1. `
```

helm: replaced deprecated repo + updated deps

---

api/src/Entity/Review.php
api/tests/ReviewsTest.php

| Deprecations? no
| Tickets       | fixes #164 
| Doc PR        | tests added
When creating a review without sending the "rating" parameter, the application raises an error 500 as a review row is being inserted without rating which is a mandatory field.

fix for #164 + regression tests

---

README.md
api/composer.json
api/config/services.yaml
api/src/Controller/LegacyApiController.php
api/src/Swagger/SwaggerDecorator.php
api/tests/Controller/LegacyApiControllerTest.php
api/tests/Controller/SwaggerTest.php

| New feature?  | yes
| Deprecations? | yes/no
| Tickets       | NA.
| Doc PR        | todo once this PR is merged.
This is a simple example showing how to extend the OpenAPI spec is order to document a legacy endpoint.

swagger: example to document a legacy endpoint

---

README.md

Fixing the link "https://api-platform.com/docs/core/swagger/" that leads to a 404

Update README.md Swagger link

---

api/composer.json
api/composer.lock

Fix the missing alice-bundle part of #227 
This is maybe a temporay fix. I would suggest to follow the dicussion here.
https://github.com/nelmio/alice/issues/1089#issuecomment-916664460
But there is more work todo to get everythink working. at least for my test-setup

fix: alice-bundle-gone. add repo-replacement

---

helm/api-platform/values.yaml

Reduce default PostgreSQL dependency resources requests, to use less nodes on Kubernetes cluster

ci: reduce default postgresql resources requests

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/cleanup.yml

setup-gcloud will be updating the branch name from master to main in a future release. Even though GitHub will establish redirects, this will break any GitHub Actions workflows that pin to master. This PR updates your GitHub Actions workflows to pin to v0, which is the recommended best practice.

Pin setup-gcloud to v0 instead of master

---

api/Dockerfile

Fix the CI with changement of the version of caddy (2.6.4 => 2.7)
Cf. https://github.com/dunglas/mercure/issues/770#issuecomment-1558154310
Fix from https://github.com/dunglas/symfony-docker/pull/407/files

fix: caddy version 2.6 to 2.7 to fix the CI

---

pwa/components/admin/Admin.tsx

| Branch?       | main 
| Tickets       | #315 
Fix the problem of pagination in open api admin
The problem was that even if we click to the pagination button in open api admin the data in the list never change and just stay the same.
To fix the problem, I add the dataProvider to the OpenApiAdmin component
For security issues please email contact@les-tilleuls.coop.

Fix pagination in the OpenAPI admin

---

.github/workflows/cd.yml
.github/workflows/check.yml
.github/workflows/deploy.yml
k6/script.js
k6/test.sh

Add a check job to the workflow, to validate the application deployment.

add check job after deployment

---

.github/workflows/ci.yml

Just a quick fix on how to retrieve CHANGED_FILES.

chore(ci): retrieve changed files from api-changed-files step
